daemon off
setup_mode off
log_level 6
log_type all

videodevice /dev/video0
v4l2_palette 17
width 1280
height 720
framerate 15

stream_port 8081
stream_localhost off
stream_auth_method 0
stream_maxrate 15
stream_quality 75

webcontrol_port 0

target_dir /recordings
movie_output on
movie_codec mp4
movie_quality 70
movie_max_time 300
movie_filename %Y/%m/%d/%Y%m%d-%H%M%S-%v

picture_output best
picture_quality 80
picture_filename %Y/%m/%d/%Y%m%d-%H%M%S-%v

pre_capture 5
post_capture 5
event_gap 15
minimum_motion_frames 3
threshold 1800
despeckle_filter EedDl
lightswitch_percent 40

on_movie_end /usr/local/barley-vision/scripts/notify-motion.sh %f
